### ISSUE TITLE
working on the Backend of The Wardrobe App

### ISSUE THREAD

**Issue by royadeveloper01** [GitCoder052023/The-Wardrobe#12]
@GitCoder052023  I would like to contribute to your open-source project as my first open-source effort after finding it in the DEV community.

**Comment by GitCoder052023** [comment]
@royadeveloper01 come on WhatsApp

**Comment by royadeveloper01** [comment]
> @royadeveloper01 come on WhatsApp

Send me your whatsapp number here.

**Comment by GitCoder052023** [comment]
@royadeveloper01 this is my number:

+91 92367 85599
